### ISSUE TITLE
FM64 note on/note off clicks & noise bursts

### ISSUE THREAD

**Issue by dukesrg** [dukesrg/logue-osc#19]
Disappears when one voice is playing note and other voices triggered the note at least once. Might be interference with the firmware part of oscillator cpu due to a high cpu load in note on routine.

**Comment by aminixduser** [comment]
Hi @dukesrg 
I took a look at the NOTE_ON.  From my somewhat limited understanding, I think most envelopes start at a zero level.
I know some synths have free wheeling lfo's and osc that aren't synch'd to a note on type of event(or have the option to enable/disable it)
So the code I suspect is this
   s_egval[i] = s_eglevel[i][EG_STAGE_COUNT - 1];
which I think is selecting the eg level for the last eg stage, and not starting at zero.  And then in OSC_CYCLE
it hits this line
    s_opval[i] = param_mul(osc_sin(modw0), eg_lut[param_mul(s_egval[i], s_oplevel[i]) >> 21]);
and boom at note on it may have an instant spike instead of something a little slower.
If your last  s_eglevel[i][ET_STAGE_COUNT-1] is zero my theory falls apart of course
I checked a few patches in dexed, and can see that the last eg level in many patches is not zero.
Also the graphical envelope of the eg shows it always starts at zero, those with high eg rates for the first stage make it look like it doesn't start at zero, but if you lower the rate a little it shows up.

**Comment by dukesrg** [comment]
@aminixduser in 6-op this is by design 
![image](https://user-images.githubusercontent.com/5592157/98774984-33577600-23fd-11eb-963a-cde3511e0f7b.png)
while 4op have zero start and end point
![image](https://user-images.githubusercontent.com/5592157/98775085-6dc11300-23fd-11eb-9d01-a5cb6ce8221a.png)

I checked with silent oscillator which returns zero out explicitly and every 4-th note have a small click on start. Either it is my XD bug or it is a voice allocation issue of a main CPU firmware (not the oscillator CPU firmware)

As for the rest of the clocks and noice bursts - it was introduced when I switched to faster EG stage adjacement based on sample count - somtimes counter misses. Looks like OSC_CYCLE have the higher priority and can even interrupt NOTE_ON/NOTE_OFF execution (yes, looks like exactly interrupt, with reentering at the interrupt point later!). So the sample counter, stage indexes and rates could become out of sync and inside the OSC_CYCLE EG level just misses the target.

**Comment by aminixduser** [comment]
Interesting choice on Yamaha's part.  I should have checked my volca fm manual, it shows the EG.  
The problem I have with this is that it implies that if you don't set L4 to 0, then you can have a note on, essentially forever, possibly only shutting off when max polyphony is exceeded on the keyboard, or perhaps a patch change.
Sure would be nice to have a good debugger based on the XD and/or NTS FW so we could see what is going on.
Another thought I had was looking back at some of the examples provided in the sdk, there is a "naive square wave" example which points out that you need a little bit of slope even on a square wave to make it sound nice, so even though it says start at L4 we start at 0, and go to L4 in 1-10 samples and you probably couldn't tell the difference between this and a dx7 or dexed.

**Comment by dukesrg** [comment]
@aminixduser DX7 allows sound forver voices, like TRAIN in the ROM1A factory bank.
And even upside-down EG's is possible. 4-op is limited to more common EG style only. 
I believe Volca FM should support full DX7-style EG aswell.

**Comment by dukesrg** [comment]
Mostly solved in c82c690
Stage index indeed must be altered at the end of NOTE_ON/NOTE_OFF, otherwise clicks are inevitable with sample-based EG.
Noise bursts was from inaccurate rate/sample count manipulations, fixed several commits earlier.

**Comment by dukesrg** [comment]
Except of the clicks produced by AEG (which is looks like per-allocated voice), only some retrigger clicks left. Mostly sporadic, so most probably just rate conditions in NOTE_ON/NOTE_OFF.

**Comment by dukesrg** [comment]
Since NOTE_ON/NOTE_OFF can be interrupted by OSC_CYCLE, the EG rates and sample count could be innacurate. Different techniques tried starting from bb001ae. In general NOTE_ON is deffered to the next OSC_CYCLE so note on clicks should not be the issue. But it is more difficult with note off, since it depends on the current eg level and sample count and still innacurate and prone to the noise/clicks.

**Comment by dukesrg** [comment]
Release clicks fixed in 43f6211. NOte on clicks depends on the CPU, including LFO routed to oscillator. Nothing to do with this other than reducing oscillator CPU consumption by disabling features.
